@typescript
Feature: TypeScript rules

  Scenario: @typescript-eslint/naming-convention rule
    Given there is typescript/naming-convention.ts file
    When file is linted against recommended-typescript ruleset
    Then file should contain 130 lint errors
    And line 3 should contain error "Variable name `aBCd` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 5 should contain error "Variable name `ABCd` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 6 should contain error "Variable name `a_bcd` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 7 should contain error "Variable name `A_BCD` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 9 should contain error "Variable name `aBcd_` must not have a trailing underscore."
    And line 10 should contain error "Variable name `_aBcd_` must not have a trailing underscore."
    And line 13 should contain error "Function name `eFGh` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 15 should contain error "Function name `EFGh` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 16 should contain error "Function name `e_fgh` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 17 should contain error "Function name `E_FGH` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 19 should contain error "Function name `eFgh_` must not have a trailing underscore."
    And line 20 should contain error "Function name `_eFgh_` must not have a trailing underscore."
    And line 22 should contain error "Class name `iJkl` must match one of the following formats: StrictPascalCase"
    And line 26 should contain error "Class name `iJKl` must match one of the following formats: StrictPascalCase"
    And line 27 should contain error "Class Method name `bAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 28 should contain error "Class Property name `fOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 34 should contain error "Class name `IJKl` must match one of the following formats: StrictPascalCase"
    And line 35 should contain error "Class Method name `BAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 36 should contain error "Class Property name `FOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 38 should contain error "Class name `i_jkl` must match one of the following formats: StrictPascalCase"
    And line 39 should contain error "Class Method name `b_aar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 40 should contain error "Class Property name `f_ooz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 42 should contain error "Class name `I_JKL` must match one of the following formats: StrictPascalCase"
    And line 43 should contain error "Class Method name `B_AAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 44 should contain error "Class Property name `F_OOZ` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 50 should contain error "Class name `IjKl_` must not have a trailing underscore."
    And line 51 should contain error "Class Method name `bAar_` must not have a trailing underscore."
    And line 52 should contain error "Class Property name `fOoz_` must not have a trailing underscore."
    And line 54 should contain error "Class name `_IjKl_` must not have a trailing underscore."
    And line 55 should contain error "Class Method name `_bAar_` must not have a trailing underscore."
    And line 56 should contain error "Class Property name `_fOoz_` must not have a trailing underscore."
    And line 59 should contain error "Enum name `mNop` must match one of the following formats: StrictPascalCase"
    And line 60 should contain error "Enum name `mNOp` must match one of the following formats: StrictPascalCase"
    And line 62 should contain error "Enum name `MNOp` must match one of the following formats: StrictPascalCase"
    And line 63 should contain error "Enum name `m_nop` must match one of the following formats: StrictPascalCase"
    And line 64 should contain error "Enum name `M_NOP` must match one of the following formats: StrictPascalCase"
    And line 66 should contain error "Enum name `MnOp_` must not have a trailing underscore."
    And line 67 should contain error "Enum name `_MnOp_` must not have a trailing underscore."
    And line 70 should contain error "Enum Member name `fooBar` must match one of the following formats: StrictPascalCase"
    And line 71 should contain error "Enum Member name `foOBar` must match one of the following formats: StrictPascalCase"
    And line 73 should contain error "Enum Member name `FOOBar` must match one of the following formats: StrictPascalCase"
    And line 74 should contain error "Enum Member name `foo_bar` must match one of the following formats: StrictPascalCase"
    And line 75 should contain error "Enum Member name `FOO_BAR` must match one of the following formats: StrictPascalCase"
    And line 77 should contain error "Enum Member name `FooBar_` must not have a trailing underscore."
    And line 78 should contain error "Enum Member name `_FooBar_` must not have a trailing underscore."
    And line 81 should contain error "Type Alias name `fooType` must match one of the following formats: StrictPascalCase"
    And line 82 should contain error "Type Alias name `foOType` must match one of the following formats: StrictPascalCase"
    And line 84 should contain error "Type Alias name `FOOType` must match one of the following formats: StrictPascalCase"
    And line 85 should contain error "Type Alias name `foo_type` must match one of the following formats: StrictPascalCase"
    And line 86 should contain error "Type Alias name `FOO_TYPE` must match one of the following formats: StrictPascalCase"
    And line 88 should contain error "Type Alias name `FooType_` must not have a trailing underscore."
    And line 89 should contain error "Type Alias name `_FooType_` must not have a trailing underscore."
    And line 93 should contain error "Type Property name `foOBar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 95 should contain error "Type Property name `FOOBar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 96 should contain error "Type Property name `foo_bar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 97 should contain error "Type Property name `FOO_BAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 99 should contain error "Type Property name `FooBar_` must not have a trailing underscore."
    And line 100 should contain error "Type Property name `_FooBar_` must not have a trailing underscore."
    And line 103 should contain error "Type Parameter name `typeParam` must match one of the following formats: StrictPascalCase"
    And line 104 should contain error "Type Parameter name `typEParam` must match one of the following formats: StrictPascalCase"
    And line 106 should contain error "Type Parameter name `TYPEParam` must match one of the following formats: StrictPascalCase"
    And line 107 should contain error "Type Parameter name `type_param` must match one of the following formats: StrictPascalCase"
    And line 108 should contain error "Type Parameter name `TYPE_PARAM` must match one of the following formats: StrictPascalCase"
    And line 110 should contain error "Type Parameter name `TypeParam_` must not have a trailing underscore."
    And line 111 should contain error "Type Parameter name `_TypeParam_` must not have a trailing underscore."
    And line 113 should contain error "Interface name `fooInterface` must match one of the following formats: StrictPascalCase"
    And line 114 should contain error "Interface name `foOInterface` must match one of the following formats: StrictPascalCase"
    And line 116 should contain error "Interface name `FOOInterface` must match one of the following formats: StrictPascalCase"
    And line 117 should contain error "Interface name `foo_interface` must match one of the following formats: StrictPascalCase"
    And line 118 should contain error "Interface name `FOO_INTERFACE` must match one of the following formats: StrictPascalCase"
    And line 120 should contain error "Interface name `FooInterface_` must not have a trailing underscore."
    And line 121 should contain error "Interface name `_FooInterface_` must not have a trailing underscore."
    And line 125 should contain error "Type Property name `foOBar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 127 should contain error "Type Property name `FOOBar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 128 should contain error "Type Property name `foo_bar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 129 should contain error "Type Property name `FOO_BAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 131 should contain error "Type Property name `FooBar_` must not have a trailing underscore."
    And line 132 should contain error "Type Property name `_FooBar_` must not have a trailing underscore."
    And line 135 should contain error "Type Parameter name `typeParam` must match one of the following formats: StrictPascalCase"
    And line 136 should contain error "Type Parameter name `typEParam` must match one of the following formats: StrictPascalCase"
    And line 138 should contain error "Type Parameter name `TYPEParam` must match one of the following formats: StrictPascalCase"
    And line 139 should contain error "Type Parameter name `type_param` must match one of the following formats: StrictPascalCase"
    And line 140 should contain error "Type Parameter name `TYPE_PARAM` must match one of the following formats: StrictPascalCase"
    And line 142 should contain error "Type Parameter name `TypeParam_` must not have a trailing underscore."
    And line 143 should contain error "Type Parameter name `_TypeParam_` must not have a trailing underscore."
    And line 149 should contain error "Variable name `qRSt` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 150 should contain error "Object Literal Method name `bAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 151 should contain error "Object Literal Property name `fOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 157 should contain error "Variable name `QRSt` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 158 should contain error "Object Literal Method name `BAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 159 should contain error "Object Literal Property name `FOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 161 should contain error "Variable name `q_rst` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 162 should contain error "Object Literal Method name `b_aar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 163 should contain error "Object Literal Property name `f_ooz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 165 should contain error "Variable name `Q_RST` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 166 should contain error "Object Literal Method name `B_aAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 167 should contain error "Object Literal Property name `F_OOZ` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 173 should contain error "Variable name `qRst_` must not have a trailing underscore."
    And line 174 should contain error "Object Literal Method name `bAar_` must not have a trailing underscore."
    And line 175 should contain error "Object Literal Property name `fOoz_` must not have a trailing underscore."
    And line 177 should contain error "Variable name `_qRst_` must not have a trailing underscore."
    And line 178 should contain error "Object Literal Method name `_bAar_` must not have a trailing underscore."
    And line 179 should contain error "Object Literal Property name `_fOoz_` must not have a trailing underscore."
    And line 186 should contain error "Variable name `vWXy` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 187 should contain error "Class Method name `bAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 188 should contain error "Class Property name `fOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 194 should contain error "Variable name `VWXy` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 195 should contain error "Class Method name `BAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 196 should contain error "Class Property name `FOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 198 should contain error "Variable name `v_wxy` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 199 should contain error "Class Method name `b_aar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 200 should contain error "Class Property name `f_ooz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 202 should contain error "Variable name `V_WXY` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 203 should contain error "Class Method name `B_aAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 204 should contain error "Class Property name `F_OOZ` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 210 should contain error "Variable name `VwXy_` must not have a trailing underscore."
    And line 211 should contain error "Class Method name `bAar_` must not have a trailing underscore."
    And line 212 should contain error "Class Property name `fOoz_` must not have a trailing underscore."
    And line 214 should contain error "Variable name `_VwXy_` must not have a trailing underscore."
    And line 215 should contain error "Class Method name `_bAar_` must not have a trailing underscore."
    And line 216 should contain error "Class Property name `_fOoz_` must not have a trailing underscore."
