@typescript
Feature: TypeScript rules

  Scenario: @typescript-eslint/naming-convention rule
    Given there is typescript/naming-convention.ts file
    When file is linted against recommended-typescript ruleset
    Then file should contain 74 lint errors
    And line 3 should contain error "Variable name `aBCd` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 5 should contain error "Variable name `ABCd` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 6 should contain error "Variable name `a_bcd` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 7 should contain error "Variable name `A_BCD` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 9 should contain error "Variable name `aBcd_` must not have a trailing underscore."
    And line 10 should contain error "Variable name `_aBcd_` must not have a trailing underscore."
    And line 13 should contain error "Function name `eFGh` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 15 should contain error "Function name `EFGh` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 16 should contain error "Function name `e_fgh` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 17 should contain error "Function name `E_FGH` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 19 should contain error "Function name `eFgh_` must not have a trailing underscore."
    And line 20 should contain error "Function name `_eFgh_` must not have a trailing underscore."
    And line 22 should contain error "Class name `iJkl` must match one of the following formats: StrictPascalCase"
    And line 26 should contain error "Class name `iJKl` must match one of the following formats: StrictPascalCase"
    And line 27 should contain error "Class Method name `bAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 28 should contain error "Class Property name `fOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 34 should contain error "Class name `IJKl` must match one of the following formats: StrictPascalCase"
    And line 35 should contain error "Class Method name `BAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 36 should contain error "Class Property name `FOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 38 should contain error "Class name `i_jkl` must match one of the following formats: StrictPascalCase"
    And line 39 should contain error "Class Method name `b_aar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 40 should contain error "Class Property name `f_ooz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 42 should contain error "Class name `I_JKL` must match one of the following formats: StrictPascalCase"
    And line 43 should contain error "Class Method name `B_AAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 44 should contain error "Class Property name `F_OOZ` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 50 should contain error "Class name `IjKl_` must not have a trailing underscore."
    And line 51 should contain error "Class Method name `bAar_` must not have a trailing underscore."
    And line 52 should contain error "Class Property name `fOoz_` must not have a trailing underscore."
    And line 54 should contain error "Class name `_IjKl_` must not have a trailing underscore."
    And line 55 should contain error "Class Method name `_bAar_` must not have a trailing underscore."
    And line 56 should contain error "Class Property name `_fOoz_` must not have a trailing underscore."
    And line 59 should contain error "Enum name `mNop` must match one of the following formats: StrictPascalCase"
    And line 60 should contain error "Enum name `mNOp` must match one of the following formats: StrictPascalCase"
    And line 62 should contain error "Enum name `MNOp` must match one of the following formats: StrictPascalCase"
    And line 63 should contain error "Enum name `m_nop` must match one of the following formats: StrictPascalCase"
    And line 64 should contain error "Enum name `M_NOP` must match one of the following formats: StrictPascalCase"
    And line 66 should contain error "Enum name `MnOp_` must not have a trailing underscore."
    And line 67 should contain error "Enum name `_MnOp_` must not have a trailing underscore."
    And line 73 should contain error "Variable name `qRSt` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 74 should contain error "Object Literal Method name `bAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 75 should contain error "Object Literal Property name `fOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 81 should contain error "Variable name `QRSt` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 82 should contain error "Object Literal Method name `BAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 83 should contain error "Object Literal Property name `FOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 85 should contain error "Variable name `q_rst` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 86 should contain error "Object Literal Method name `b_aar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 87 should contain error "Object Literal Property name `f_ooz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 89 should contain error "Variable name `Q_RST` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 90 should contain error "Object Literal Method name `B_aAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 91 should contain error "Object Literal Property name `F_OOZ` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 97 should contain error "Variable name `qRst_` must not have a trailing underscore."
    And line 98 should contain error "Object Literal Method name `bAar_` must not have a trailing underscore."
    And line 99 should contain error "Object Literal Property name `fOoz_` must not have a trailing underscore."
    And line 101 should contain error "Variable name `_qRst_` must not have a trailing underscore."
    And line 102 should contain error "Object Literal Method name `_bAar_` must not have a trailing underscore."
    And line 103 should contain error "Object Literal Property name `_fOoz_` must not have a trailing underscore."
    And line 110 should contain error "Variable name `vWXy` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 111 should contain error "Class Method name `bAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 112 should contain error "Class Property name `fOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 118 should contain error "Variable name `VWXy` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 119 should contain error "Class Method name `BAAr` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 120 should contain error "Class Property name `FOOz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 122 should contain error "Variable name `v_wxy` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 123 should contain error "Class Method name `b_aar` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 124 should contain error "Class Property name `f_ooz` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 126 should contain error "Variable name `V_WXY` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 127 should contain error "Class Method name `B_aAR` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 128 should contain error "Class Property name `F_OOZ` must match one of the following formats: strictCamelCase, StrictPascalCase"
    And line 134 should contain error "Variable name `VwXy_` must not have a trailing underscore."
    And line 135 should contain error "Class Method name `bAar_` must not have a trailing underscore."
    And line 136 should contain error "Class Property name `fOoz_` must not have a trailing underscore."
    And line 138 should contain error "Variable name `_VwXy_` must not have a trailing underscore."
    And line 139 should contain error "Class Method name `_bAar_` must not have a trailing underscore."
    And line 140 should contain error "Class Property name `_fOoz_` must not have a trailing underscore."
