name: Prepare release
on:
  workflow_dispatch:
    inputs:
      rev:
        description: Git revision to prepare release from
        required: true
        default: master
      version:
        description: Version number of the release
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rev }}
          # scripts/ci/prepare-release.sh depends on git tags being fetched.
          fetch-depth: 0
      # Fix `fatal: detected dubious ownership in repository at '/__w/eslint-config/eslint-config'`
      # error that occurs during this step. Since version 2.35.2 `git` has not
      # liked that the git directory is owned by other user than the one
      # performing git operations in the directory. Change the owner of the
      # directory to be the same user as these steps are run as.
      - run: chown root:root "$GITHUB_WORKSPACE"
      - run: scripts/ci/prepare-release.sh '${{ github.event.inputs.version }}' '${{ github.actor }}'
