name: Prepare release
on:
  workflow_dispatch:
    inputs:
      rev:
        description: Git revision to prepare release from
        required: true
        default: master
      version:
        description: Version number of the release
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.rev }}
          # scripts/ci/prepare-release.sh depends on git tags being fetched.
          fetch-depth: 0
      - run: scripts/ci/prepare-release.sh '${{ github.event.inputs.version }}' '${{ github.actor }}'
