name: Release
on:
  workflow_dispatch:
    inputs:
      rev:
        description: Git revision to release
        required: true
        default: release-1.0.0

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rev }}
      - run: scripts/ci/audit.sh

  lint:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    needs: audit
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rev }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-dependencies-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --cache ~/.npm --prefer-offline --ignore-scripts --no-fund
      # Fix `fatal: detected dubious ownership in repository at '/__w/eslint-config/eslint-config'`
      # error that occurs during this step. Since version 2.35.2 `git` has not
      # liked that the git directory is owned by other user than the one
      # performing git operations in the directory. Change the owner of the
      # directory to be the same user as these steps are run as.
      - run: chown root:root "$GITHUB_WORKSPACE"
      - run: scripts/lint.sh paths .

  test:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    needs: lint # Run after lint so that audit job has an opportunity to fill npm cache.
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rev }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-dependencies-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --cache ~/.npm --prefer-offline --ignore-scripts --no-fund
      - run: chown root:root "$GITHUB_WORKSPACE"
      - run: scripts/test.sh

  type-check:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    needs: lint # Run after lint so that audit job has an opportunity to fill npm cache.
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rev }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-dependencies-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --cache ~/.npm --prefer-offline --ignore-scripts --no-fund
      - run: chown root:root "$GITHUB_WORKSPACE"
      - run: scripts/type-check.sh

  release:
    runs-on: ubuntu-latest
    container:
      image: response200/node-build:latest
      options: --user root:root
    needs: [test, type-check]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rev }}
          # scripts/ci/release.sh depends on all git branches being fetched.
          fetch-depth: 0
      - run: chown root:root "$GITHUB_WORKSPACE"
      - run: scripts/ci/release.sh '${{ github.event.inputs.rev }}' '${{ github.actor }}'
        env:
          TOKEN_FOR_PUBLISHING_NPM_PACKAGES: ${{ secrets.TOKEN_FOR_PUBLISHING_NPM_PACKAGES }}
